title: My Github Project
author: Peter W
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My Blog for writing nothing but indescript words to entertain no-one

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
